#!/bin/bash

# =============================
# Run as ROOT only
# =============================

set -e

echo "Updating system..."
apt update -y
apt upgrade -y
sudo apt update
sudo apt install ufw -y
echo "Installing base packages..."
apt install -y \
openjdk-21-jdk \
net-tools \
openssh-server \
python3 \
nano \
firewalld \
iproute2 \
software-properties-common \
iputils-ping \
ufw \
ca-certificates \
curl

# =============================
# Install Ansible
# =============================
echo "Installing Ansible..."

add-apt-repository --yes --update ppa:ansible/ansible
apt update -y
apt install -y ansible

# =============================
# Install Docker
# =============================
echo "Installing Docker..."

install -m 0755 -d /etc/apt/keyrings

curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
-o /etc/apt/keyrings/docker.asc

chmod a+r /etc/apt/keyrings/docker.asc

echo \
"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
https://download.docker.com/linux/ubuntu \
$(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
| tee /etc/apt/sources.list.d/docker.list > /dev/null

apt update -y

apt install -y \
docker-ce \
docker-ce-cli \
containerd.io \
docker-buildx-plugin \
docker-compose-plugin

# Enable docker
systemctl enable docker
systemctl start docker

echo "Installation Completed Successfully!"
